version: '3.8'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 51563:1972
      - 52563:52773
      - 53773
    # network_mode: "host"
    volumes:
    # - ~/iris.key:/usr/irissys/mgr/iris.key
      - ./:/irisdev/app